print("run 1")
system("Rscript 02_links_process.R 100", wait=FALSE)
print("run 2")
system("Rscript 02_links_process.R 100", wait=FALSE)
print("run 3")
system("Rscript 02_links_process.R 100", wait=FALSE)
print("run 4")
system("Rscript 03_pages_process.R 100", wait=FALSE)
print("run 5")
system("Rscript 03_pages_process.R 100", wait=FALSE)
print("run 6")
system("Rscript 03_pages_process.R 100", wait=FALSE)