source("00_dbmongo.R")

crontabToAdd <- c()
#crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 00; sar 1 5 > cpu_performance_temp.log; mv cpu_performance_temp.log cpu_performance.log # LENTA R SCRIPT')
#crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 10; sar 1 5 > cpu_performance_temp.log; mv cpu_performance_temp.log cpu_performance.log # LENTA R SCRIPT')
#crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 20; sar 1 5 > cpu_performance_temp.log; mv cpu_performance_temp.log cpu_performance.log # LENTA R SCRIPT')
#crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 30; sar 1 5 > cpu_performance_temp.log; mv cpu_performance_temp.log cpu_performance.log # LENTA R SCRIPT')
#crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 40; sar 1 5 > cpu_performance_temp.log; mv cpu_performance_temp.log cpu_performance.log # LENTA R SCRIPT')
#crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 50; sar 1 5 > cpu_performance_temp.log; mv cpu_performance_temp.log cpu_performance.log # LENTA R SCRIPT')
crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 00; Rscript 00_run_processes.R >> process_t.log; mv process_t.log process.log # LENTA R SCRIPT')
crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 10; Rscript 00_run_processes.R >> process_t.log; mv process_t.log process.log # LENTA R SCRIPT')
crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 20; Rscript 00_run_processes.R >> process_t.log; mv process_t.log process.log # LENTA R SCRIPT')
crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 30; Rscript 00_run_processes.R >> process_t.log; mv process_t.log process.log # LENTA R SCRIPT')
crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 40; Rscript 00_run_processes.R >> process_t.log; mv process_t.log process.log # LENTA R SCRIPT')
crontabToAdd <- c(crontabToAdd, '* *   * * *   cd /home/ildar/lentaproject/; sleep 50; Rscript 00_run_processes.R >> process_t.log; mv process_t.log process.log # LENTA R SCRIPT')

#crontabToAdd <- c()
crontab <- system('crontab -l', intern = TRUE)
lentaCron <- grep("# LENTA", crontab)
if (length(lentaCron)!=0) {crontab <- crontab[-lentaCron]}
crontab <- c(crontab, crontabToAdd)
writeLines(crontab, "current_cron")
crontab <- system('crontab current_cron', intern = TRUE)
