source("00_dbmongo.R")

cpu <- GetCPULoadFromLog()
dt <- GetPerformance()
cpusum <- sum(dt$cpu)
dtStatus <- GetDBStatus()
print(paste0("---------------------"))
print(paste0("REPORT: ", format(Sys.time(), "%Y-%m-%d-%H-%M-%S %Z")))
print(paste0("CPU log: ", cpu))
print(paste0("CPU act: ", cpusum))
print(paste0("ACTIVE PROCESSES:"))
print(as.data.frame(dt))
print(paste0("CURRENT DB STATUS:"))
print(as.data.frame(dtStatus))
